remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Juan Esteban Rendon Torres
submodulo: Nuevas tecnologias de programacion 
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/evidencias-75c7d.appspot.com/o/foto%20mia.jpg?alt=media&token=fa17447e-ddfc-48a5-8a45-effd8ec58023

